// Thin wrapper over fetch for the AutoPivot API.
//
// Requests go to same-origin paths; Vite proxies /auth and /api to FastAPI in
// development, and in production both are served from one host.

const TOKEN_KEY = 'autopivot.token'

export type Dealership = {
  id: number
  name: string
  location: string | null
  status: string
  user_count: number
}

export type User = {
  id: number
  email: string
  first_name: string
  last_name: string
  role: 'platform_admin' | 'dealership_admin' | 'dealership_staff'
  is_active: boolean
  must_change_password: boolean
  dealership: Dealership | null
}

export type LoginResponse = {
  access_token: string
  token_type: string
  expires_in: number
  user: User
}

export type NavCounts = {
  vehicles: number
  backdrops: number
  needs_review: number
}

export type DashboardStats = {
  vehicles_this_month: number
  images_processed: number
  needs_review: number
}

export type ProcessingStatus = 'pending' | 'processing' | 'complete' | 'needs_review'

export type VehicleListing = {
  id: number
  stock_number: string | null
  title: string
  make: string
  model: string
  year: number
  variant: string | null
  price: string | null
  status: string
  processing_status: ProcessingStatus
  image_count: number
  created_at: string
  updated_at: string
}

export type ListingImage = {
  id: number
  image_type: 'original' | 'processed' | 'background' | 'plate_overlay'
  original_filename: string
  image_url: string
  width: number
  height: number
  file_size_bytes: number
  created_at: string
}

export type VehicleListingDetail = VehicleListing & {
  description: string | null
  images: ListingImage[]
}

export type VehicleListingCreate = {
  make: string
  model: string
  year: number
  variant?: string | null
  stock_number?: string | null
  price?: number | null
}

export type ProcessingJob = {
  id: number
  status: 'pending' | 'processing' | 'completed' | 'failed'
  processing_type: string
  input_image_id: number
  output_image_id: number | null
  output_image_url: string | null
  backdrop_id: number | null
  detected_angle: string | null
  angle_confidence: string | null
  plates_detected: number | null
  plate_treatment: string | null
  review_state: 'ok' | 'needs_review' | null
  model_used: string | null
  error_message: string | null
  started_at: string | null
  completed_at: string | null
}

export type ProcessingSummary = {
  listing_id: number
  processing_status: ProcessingStatus
  total: number
  completed: number
  failed: number
  needs_review: number
  jobs: ProcessingJob[]
}

export type Backdrop = {
  id: number
  name: string
  /** Empty means the backdrop suits all angles. */
  suits_angles: string[]
  is_default: boolean
  image_url: string
  created_at: string
}

/** An API error carrying the status code, so callers can treat 401 specially. */
export class ApiError extends Error {
  status: number
  constructor(status: number, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

export const tokenStore = {
  get: () => localStorage.getItem(TOKEN_KEY),
  set: (token: string) => localStorage.setItem(TOKEN_KEY, token),
  clear: () => localStorage.removeItem(TOKEN_KEY),
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const token = tokenStore.get()
  const headers = new Headers(init.headers)
  // FormData must set its own Content-Type, because the multipart boundary is
  // generated by the browser and cannot be written by hand.
  if (!(init.body instanceof FormData)) headers.set('Content-Type', 'application/json')
  if (token) headers.set('Authorization', `Bearer ${token}`)

  let response: Response
  try {
    response = await fetch(path, { ...init, headers })
  } catch {
    // fetch only rejects on network failure, never on a 4xx or 5xx.
    throw new ApiError(0, 'Could not reach the server. Is the API running?')
  }

  if (response.status === 204) return undefined as T

  const body = await response.json().catch(() => null)

  if (!response.ok) {
    // FastAPI puts a string in `detail` for our raised errors, and an array of
    // validation objects for 422s. Neither is safe to render directly.
    const detail = body?.detail
    const message =
      typeof detail === 'string'
        ? detail
        : Array.isArray(detail)
          ? detail.map((d: { msg?: string }) => d.msg).filter(Boolean).join('. ')
          : `Request failed (${response.status}).`
    throw new ApiError(response.status, message)
  }

  return body as T
}

export const api = {
  login: (email: string, password: string) =>
    request<LoginResponse>('/auth/login', {
      method: 'POST',
      body: JSON.stringify({ email, password }),
    }),

  me: () => request<User>('/auth/me'),

  changePassword: (current_password: string, new_password: string) =>
    request<User>('/auth/change-password', {
      method: 'POST',
      body: JSON.stringify({ current_password, new_password }),
    }),

  dashboardStats: () => request<DashboardStats>('/api/dashboard/stats'),

  navCounts: () => request<NavCounts>('/api/dashboard/counts'),

  listing: (id: number) => request<VehicleListingDetail>(`/api/listings/${id}`),

  createListing: (payload: VehicleListingCreate) =>
    request<VehicleListingDetail>('/api/listings', {
      method: 'POST',
      body: JSON.stringify(payload),
    }),

  deleteListing: (id: number) =>
    request<void>(`/api/listings/${id}`, { method: 'DELETE' }),

  uploadImages: (listingId: number, files: File[]) => {
    const body = new FormData()
    // The field repeats once per file: FastAPI collects them into list[UploadFile].
    for (const file of files) body.append('files', file)
    return request<ListingImage[]>(`/api/listings/${listingId}/images`, {
      method: 'POST',
      body,
    })
  },

  deleteImage: (listingId: number, imageId: number) =>
    request<void>(`/api/listings/${listingId}/images/${imageId}`, { method: 'DELETE' }),

  processListing: (listingId: number, backdropId: number | null) =>
    request<ProcessingSummary>(`/api/listings/${listingId}/process`, {
      method: 'POST',
      body: JSON.stringify({ backdrop_id: backdropId }),
    }),

  listingJobs: (listingId: number) =>
    request<ProcessingSummary>(`/api/listings/${listingId}/jobs`),

  backdrops: () => request<Backdrop[]>('/api/backdrops'),

  createBackdrop: (name: string, file: File, suitsAngles: string[] = []) => {
    const body = new FormData()
    body.append('name', name)
    body.append('file', file)
    body.append('suits_angles', suitsAngles.join(','))
    return request<Backdrop>('/api/backdrops', { method: 'POST', body })
  },

  deleteBackdrop: (id: number) =>
    request<void>(`/api/backdrops/${id}`, { method: 'DELETE' }),

  /** Stored files are behind auth, so they cannot be used as a plain <img src>. */
  fetchFile: async (url: string): Promise<string> => {
    const response = await fetch(url, {
      headers: { Authorization: `Bearer ${tokenStore.get() ?? ''}` },
    })
    if (!response.ok) throw new ApiError(response.status, 'Image unavailable.')
    return URL.createObjectURL(await response.blob())
  },

  listings: (
    params: { limit?: number; processing_status?: ProcessingStatus; q?: string } = {},
  ) => {
    const query = new URLSearchParams()
    if (params.limit !== undefined) query.set('limit', String(params.limit))
    if (params.processing_status) query.set('processing_status', params.processing_status)
    if (params.q) query.set('q', params.q)
    const suffix = query.toString() ? `?${query}` : ''
    return request<VehicleListing[]>(`/api/listings${suffix}`)
  },
}
