"""create initial database schema

Revision ID: f47ee772826e
Revises: 
Create Date: 2026-08-05 16:28:55.364577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47ee772826e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealerships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'closed')", name=op.f('ck_dealerships_status_allowed')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_dealerships_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealerships'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dealership_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'platform_admin' AND dealership_id IS NULL) OR (role IN ('dealership_admin', 'dealership_staff') AND dealership_id IS NOT NULL)", name=op.f('ck_users_role_matches_dealership')),
    sa.CheckConstraint("role IN ('platform_admin', 'dealership_admin', 'dealership_staff')", name=op.f('ck_users_role_allowed')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.CheckConstraint('length(trim(email)) > 0', name=op.f('ck_users_email_not_blank')),
    sa.CheckConstraint('length(trim(first_name)) > 0', name=op.f('ck_users_first_name_not_blank')),
    sa.CheckConstraint('length(trim(last_name)) > 0', name=op.f('ck_users_last_name_not_blank')),
    sa.CheckConstraint('length(trim(password_hash)) > 0', name=op.f('ck_users_password_hash_not_blank')),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_users_dealership_id_dealerships'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('id', 'dealership_id', name='user_dealership_pair')
    )
    op.create_index(op.f('ix_users_dealership_id'), 'users', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicle_listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dealership_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'sold', 'archived')", name=op.f('ck_vehicle_listings_status_allowed')),
    sa.CheckConstraint('length(trim(make)) > 0', name=op.f('ck_vehicle_listings_make_not_blank')),
    sa.CheckConstraint('length(trim(model)) > 0', name=op.f('ck_vehicle_listings_model_not_blank')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_vehicle_listings_title_not_blank')),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('ck_vehicle_listings_price_non_negative')),
    sa.CheckConstraint('year BETWEEN 1886 AND 2100', name=op.f('ck_vehicle_listings_year_range')),
    sa.ForeignKeyConstraint(['created_by_user_id', 'dealership_id'], ['users.id', 'users.dealership_id'], name='creator_same_dealership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name=op.f('fk_vehicle_listings_dealership_id_dealerships'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_listings'))
    )
    op.create_index(op.f('ix_vehicle_listings_created_by_user_id'), 'vehicle_listings', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_listings_dealership_id'), 'vehicle_listings', ['dealership_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('image_type', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("image_type IN ('original', 'processed', 'background', 'plate_overlay')", name=op.f('ck_images_type_allowed')),
    sa.CheckConstraint("mime_type IN ('image/jpeg', 'image/png', 'image/webp')", name=op.f('ck_images_mime_type_allowed')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_images_file_size_positive')),
    sa.CheckConstraint('height > 0', name=op.f('ck_images_height_positive')),
    sa.CheckConstraint('length(trim(original_filename)) > 0', name=op.f('ck_images_original_filename_not_blank')),
    sa.CheckConstraint('length(trim(storage_path)) > 0', name=op.f('ck_images_storage_path_not_blank')),
    sa.CheckConstraint('width > 0', name=op.f('ck_images_width_positive')),
    sa.ForeignKeyConstraint(['vehicle_listing_id'], ['vehicle_listings.id'], name=op.f('fk_images_vehicle_listing_id_vehicle_listings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('id', 'vehicle_listing_id', name='image_listing_pair'),
    sa.UniqueConstraint('storage_path', name=op.f('uq_images_storage_path'))
    )
    op.create_index(op.f('ix_images_vehicle_listing_id'), 'images', ['vehicle_listing_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('input_image_id', sa.BigInteger(), nullable=False),
    sa.Column('output_image_id', sa.BigInteger(), nullable=True),
    sa.Column('background_image_id', sa.BigInteger(), nullable=True),
    sa.Column('plate_overlay_image_id', sa.BigInteger(), nullable=True),
    sa.Column('processing_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_type IN ('full_pipeline', 'background_removal', 'plate_detection')", name=op.f('ck_processing_jobs_processing_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_processing_jobs_status_allowed')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_processing_jobs_completion_after_start')),
    sa.ForeignKeyConstraint(['background_image_id', 'vehicle_listing_id'], ['images.id', 'images.vehicle_listing_id'], name='background_image_same_listing', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['input_image_id', 'vehicle_listing_id'], ['images.id', 'images.vehicle_listing_id'], name='input_image_same_listing', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['output_image_id', 'vehicle_listing_id'], ['images.id', 'images.vehicle_listing_id'], name='output_image_same_listing', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plate_overlay_image_id', 'vehicle_listing_id'], ['images.id', 'images.vehicle_listing_id'], name='plate_overlay_image_same_listing', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_listing_id'], ['vehicle_listings.id'], name=op.f('fk_processing_jobs_vehicle_listing_id_vehicle_listings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_vehicle_listing_id'), 'processing_jobs', ['vehicle_listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_vehicle_listing_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_images_vehicle_listing_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_vehicle_listings_dealership_id'), table_name='vehicle_listings')
    op.drop_index(op.f('ix_vehicle_listings_created_by_user_id'), table_name='vehicle_listings')
    op.drop_table('vehicle_listings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dealership_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('dealerships')
    # ### end Alembic commands ###
